In [3]:
import numpy as np
matrix = np.matrix([[0.9,0.08,0.035],
                   [0.08,0.9,0.035], 
                   [0.035,0.035,0.9]], dtype=float)
vector = np.matrix([[0.3,0.5,0.2]], dtype=float)
for i in range(1000):
    vector = vector * matrix
    print('current cnt: ', i + 1)
    print(vector)

current cnt:  1
[[0.317 0.481 0.208]]
current cnt:  2
[[0.33106 0.46554 0.21513]]
current cnt:  3
[[0.34272675 0.45300035 0.221498  ]]
current cnt:  4
[[0.35244653 0.44287088 0.22719865]]
current cnt:  5
[[0.3605835  0.43473147 0.23231489]]
current cnt:  6
[[0.36743469 0.42823603 0.23691943]]
current cnt:  7
[[0.37324228 0.42309938 0.24107596]]
current cnt:  8
[[0.37820367 0.41908648 0.24484032]]
current cnt:  9
[[0.38247963 0.41600354 0.24826145]]
current cnt:  10
[[0.3862011  0.41369071 0.25138221]]
current cnt:  11
[[0.38947462 0.4120161  0.2542402 ]]
current cnt:  12
[[0.39238686 0.41087087 0.25686836]]
current cnt:  13
[[0.39500823 0.41016512 0.25929554]]
current cnt:  14
[[0.39739596 0.40982461 0.26154706]]
current cnt:  15
[[0.39959648 0.40978797 0.26364507]]
current cnt:  16
[[0.40164745 0.41000447 0.26560902]]
current cnt:  17
[[0.40357938 0.41043214 0.26745594]]
current cnt:  18
[[0.40541697 0.41103623 0.26920074]]
current cnt:  19
[[0.4071802  0.41178799 0.27085653]]
current